"""🔴 SUPERSEDED for narration — this made `scored.mp4`, not the current cut.

The intro film's narration is now generated by `warm-natural-v2/`, whose Chatterbox performance
was approved where this tool's edge-tts voice plus the `voice_chain` humanising pass was not.
The method is in `../../natural-voice/README.md`. Keep this for reproducing `scored.mp4`; do not
start new narration here. Its siblings — `intro_cues.py`, `intro_score.py`, `intro_mux.py` and
`check_intro.py` — are not voice tools and are unaffected.

Speak the intro film's narration, one WAV per line, timed to the cut.

    python education-video/examples/intro/audio/intro_narrate.py --cues out/education/audio/cues.json \
        --out out/education/audio/vo

The lines and their timecodes come from `voiceover-script.md` via `intro_cues.py`; nothing is
copied here. Each line becomes `vo_<frame>.wav`, 48 kHz mono, whose first sample is the first
sample of speech -- the mixer places the file at `(frame - 1) / 30` and the contract is that
t = 0 in the file is the moment the narrator starts, not the moment the API started encoding.

Three things this does that a plain call to a TTS API does not.

  It fits each line to its slot. The picture is cut to these timecodes, so a line that speaks
  for longer than the gap before the next one is a fault, and the fix is rate: each line is
  spoken at the *slowest* rate that fits. Where no rate fits, the line may start early -- into
  the silence the previous line left, never into the previous line's speech, and never by more
  than LEAD. A sentence that arrives a third of a second before the thing it describes is
  ordinary narration; a sentence that runs into the next one is a fault. A line that still
  does not fit is printed loudly: that one needs a shorter sentence, which is an edit to the
  script and not to this file.

  It trims. edge-tts pads the front of a line by a few milliseconds to a few tenths, and that
  padding would show up as the narrator being late against the visual he is describing.

  It checks its own pronunciation, as far as that can be checked without listening. The API
  reports a spoken duration per token, so a token that takes far longer than its length
  suggests is being expanded into more words than it looks like -- which is how the four
  substitutions in SPOKEN were found rather than guessed. Anything else suspicious is flagged.

The voice is Microsoft's neural TTS over the network via `edge-tts` (no key, no account, but
the text does leave the machine). `--chain none` gives the model's own output untouched.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import edge_tts
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from intro_cues import frame_of  # noqa: E402
from intro_env import OUT, find_ffmpeg  # noqa: E402

from dsp import SR, highpass, read_wav, spectral, write_wav24  # noqa: E402
from voice_chain import compress, deess, humanise  # noqa: E402

FPS = 30

# The candidates, and Microsoft's own personality tags where they describe the model well. The
# Multilingual models are a later generation than the plain Neural ones and phrase where the
# older ones recite; `en-GB-RyanNeural` is here only because it is what the assembly film's
# first pass used and was rejected as "the most announcer".
VOICES = {
    "en-US-AndrewMultilingualNeural": "warm, confident, authentic, honest -- the default",
    "en-US-BrianMultilingualNeural": "approachable, casual, sincere; lighter than Andrew",
    "en-US-AvaMultilingualNeural": "female, bright, expressive",
    "en-US-EmmaMultilingualNeural": "female, warmer and slower than Ava",
    "en-AU-WilliamMultilingualNeural": "Australian, friendly, a little drier",
    "en-GB-RyanNeural": "older model: British, formal, the most 'announcer'",
}

# Substitutions applied to the *spoken* text only. The document keeps its typography; this is
# the one place that knows how to say it. Each one was measured, not assumed -- the API reports
# how long it spent on a token, and a quantity that takes longer than its syllables should is
# being read as something else:
#
#   "AD7124-8"  2.81 s  ->  "seven thousand one hundred twenty-four dash eight". Spelling the
#                           digits out costs 2.0 s and is how the part is actually said.
#   "22 kΩ"     1.65 s  ->  1.02 s as "22 kilohms", so the raw form was adding a word.
#   "2.5 V"     "V" in 0.15 s is the letter, not the unit.
#   "0.21"      1.84 s  ->  1.35 s spelled out; the raw form is not saying "two one".
#
# MAX1968 (1.59 s) and 25 °C (1.90 s) both measure as correct -- "max nineteen sixty-eight"
# and "twenty-five degrees Celsius" -- so they are deliberately left alone.
SPOKEN = (
    ("AD7124-8", "A-D seven one two four dash eight"),
    ("22 kΩ", "22 kilohms"),
    ("2.5 V", "2.5 volt"),
    ("0.21 millikelvin", "zero point two one millikelvin"),
)

# A token this long is worth a look: no plain number or unit in this script takes more than
# about a second to say, so anything past this is being expanded.
TOKEN_SUSPECT = 1.25
RISKY = re.compile(r"[\d°Ωµ]")

# Rate steps tried, in order, when a line overruns its slot. Small steps: the fitter should
# take the least it can get away with, and +16 % is already a noticeably hurried delivery.
RATE_STEPS = (0, 4, 8, 12, 16)
# Speech has to end this long before the next line starts, or they tread on each other.
MARGIN = 0.10
# How early a line may start when no rate fits, and how much silence to leave behind the
# previous line when it does. Narration that leads its picture slightly is normal; narration
# that overlaps the sentence before it is not, so the guard is never traded away.
LEAD = 0.60
GUARD = 0.15


def spoken_text(text: str) -> str:
    for a, b in SPOKEN:
        text = text.replace(a, b)
    return text


async def speak(text: str, voice: str, rate: str, pitch: str):
    """One request; returns the MP3 bytes and the per-token timings from the same stream."""
    audio, toks = bytearray(), []
    comm = edge_tts.Communicate(text, voice, rate=rate, pitch=pitch, boundary="WordBoundary")
    async for chunk in comm.stream():
        if chunk["type"] == "audio":
            audio += chunk["data"]
        elif chunk["type"] == "WordBoundary":
            toks.append((chunk["text"], chunk["duration"] / 1e7))
    return bytes(audio), toks


def decode(ffmpeg: str, mp3: bytes, tmp: Path) -> np.ndarray:
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_bytes(mp3)
    wav = tmp.with_suffix(".dec.wav")
    subprocess.run([ffmpeg, "-y", "-loglevel", "error", "-i", str(tmp),
                    "-ar", str(SR), "-ac", "1", str(wav)], check=True)
    x = read_wav(wav)[0]
    tmp.unlink(missing_ok=True)
    wav.unlink(missing_ok=True)
    return x


def trim(x: np.ndarray, pre: float = 0.008, tail: float = 0.06):
    """Cut the API's leading pad so t = 0 is the start of speech, and drop the trailing
    silence. Threshold is relative to the line's own peak, so a quiet line is not trimmed
    into its first consonant."""
    env = np.abs(x)
    thresh = max(env.max() * 10 ** (-45 / 20.0), 1e-5)
    loud = np.flatnonzero(env > thresh)
    if len(loud) == 0:
        return x, 0.0
    a = max(0, loud[0] - int(pre * SR))
    b = min(len(x), loud[-1] + int(tail * SR))
    return x[a:b], a / SR


def say(ffmpeg: str, cache: Path, text: str, voice: str, rate: str, pitch: str):
    """One spoken line, trimmed, plus its token timings -- from the cache when the exact same
    request has been made before. The fitter asks for the same line at several rates and the
    mix gets re-cut far more often than the words change, so caching turns a couple of idle
    minutes of network per run into nothing, and makes a re-mix reproducible without the
    network at all. The key is everything the request depends on."""
    key = hashlib.sha1("|".join((voice, rate, pitch, text)).encode()).hexdigest()[:16]
    wav, meta = cache / f"{key}.wav", cache / f"{key}.json"
    if wav.exists() and meta.exists():
        d = json.loads(meta.read_text(encoding="utf-8"))
        return read_wav(wav)[0], d["tokens"], d["pad"], True
    mp3, toks = asyncio.run(speak(text, voice, rate, pitch))
    x, pad = trim(decode(ffmpeg, mp3, cache / f"{key}.mp3"))
    write_wav24(wav, x)
    meta.write_text(json.dumps(dict(voice=voice, rate=rate, pitch=pitch, text=text,
                                    pad=pad, tokens=toks), ensure_ascii=False),
                    encoding="utf-8")
    return x, toks, pad, False


def chain(x: np.ndarray, mode: str, wet: float) -> np.ndarray:
    """`light` is corrective only -- rumble out, sibilance held down, level steadied. It does
    not try to change what the model sounds like, because the two attempts at that on the
    assembly film were both rejected and the heavier one was rejected harder."""
    if mode == "none":
        return x
    if mode == "full":
        return humanise(x, wet=wet)
    x = spectral(x, lambda f: highpass(f, 75, 3))
    return compress(deess(x), thresh_db=-22.0, ratio=3.0)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cues", type=Path, default=OUT / "audio" / "cues.json")
    ap.add_argument("--out", type=Path, default=OUT / "audio" / "vo")
    ap.add_argument("--voice", default="en-US-AndrewMultilingualNeural")
    ap.add_argument("--rate", type=int, default=0, help="base rate, per cent")
    ap.add_argument("--pitch", default="+0Hz", help="left alone by default")
    ap.add_argument("--chain", choices=("none", "light", "full"), default="light")
    ap.add_argument("--wet", type=float, default=0.13, help="room level, --chain full only")
    ap.add_argument("--cache", type=Path, default=OUT / "audio" / "_tts-cache",
                    help="decoded TTS, keyed by voice+rate+text; delete it to force a re-fetch")
    ap.add_argument("--only", help="1-based line numbers, e.g. 1,3,20-22 -- for auditions")
    ap.add_argument("--audition", type=Path,
                    help="write one file of the selected lines back to back instead")
    ap.add_argument("--list", action="store_true", help="print the candidate voices and exit")
    args = ap.parse_args()

    if args.list:
        for name, why in VOICES.items():
            print(f"  {name:34s} {why}")
        return 0

    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        sys.exit("ffmpeg not found; it decodes what edge-tts returns")
    cues = json.loads(args.cues.read_text(encoding="utf-8"))
    lines = cues["lines"]

    if args.only:
        want = set()
        for part in args.only.split(","):
            if "-" in part:
                a, b = part.split("-")
                want |= set(range(int(a), int(b) + 1))
            else:
                want.add(int(part))
        lines = [l for i, l in enumerate(lines, 1) if i in want]

    args.out.mkdir(parents=True, exist_ok=True)
    # The mixer globs this directory, so a line that moves in the script would otherwise leave
    # its old file behind and the narrator would say both. This exact fault cost the assembly
    # film a mix with sixteen lines in it instead of eleven.
    if not args.audition:
        stale = sorted(args.out.glob("vo_*.wav"))
        for f in stale:
            f.unlink()
        if stale:
            print(f"  cleared {len(stale)} file(s) from a previous run")

    print(f"{args.voice}  rate {args.rate:+d}%  pitch {args.pitch}  chain {args.chain}"
          f"{'' if args.chain != 'full' else f' (room {args.wet:.0%})'}   {len(lines)} lines")

    made, suspect, fitted, early, kept, raw = [], [], [], [], [], []
    hits, takes_total, prev_end = 0, 0, -1e9
    for i, l in enumerate(lines):
        text = spoken_text(l["text"])
        room = 1e9 if args.audition else l["slot"] - MARGIN
        # Everything the previous line left unused, minus the guard, up to the cap.
        can_lead = 0.0 if args.audition else max(0.0, min(LEAD, l["t"] - prev_end - GUARD))
        takes = []
        for step in RATE_STEPS:
            rate = f"{args.rate + step:+d}%"
            x, toks, pad, cached = say(ffmpeg, args.cache, text, args.voice, rate, args.pitch)
            hits += cached
            takes_total += 1
            takes.append((rate, x, toks, pad))
            if len(x) / SR <= room:
                break
        rate, x, toks, pad = next((t for t in takes if len(t[1]) / SR <= room), takes[-1])
        dur = len(x) / SR
        lead = min(can_lead, max(0.0, dur - room))
        over = dur - room - lead
        flag = "" if over <= 0 else f"  OVERRUNS by {over:.2f} s"
        if rate != f"{args.rate:+d}%":
            fitted.append((l["frame"], rate))
        if lead > 0.005:
            early.append((l["frame"], lead))
        if over > 0:
            kept.append((l["frame"], over))
        start = l["t"] - lead
        prev_end = start + dur
        made.append(dict(frame=frame_of(start), sched_frame=l["frame"], t=l["t"],
                         start=round(start, 3), lead=round(lead, 3), slot=l["slot"],
                         dur=round(dur, 3), rate=rate, pad=round(pad, 3), words=l["words"],
                         text=l["text"], spoken=text, scene=l["scene"]))
        print(f"  {i + 1:2d}. f{l['frame']:5d}  {l['t']:7.2f} s  {dur:5.2f}/{l['slot']:5.2f} s"
              f"  {l['words']:2d} w  {rate:>4s}  pad {pad * 1000:4.0f} ms"
              f"  {'' if lead <= 0.005 else f'-{lead:.2f} s early'}{flag}")
        for w, d in toks:
            if d > TOKEN_SUSPECT and RISKY.search(w):
                suspect.append((l["frame"], w, d))
        raw.append(x)

    processed = [chain(x, args.chain, args.wet) for x in raw]
    # One gain for all of them, taken from the loudest line, so the quiet lines stay quiet. A
    # narrator whose every sentence is equally loud is one of the things that reads as machine.
    peak = max(float(np.abs(p).max()) for p in processed)
    scale = 0.89 / max(peak, 1e-9)

    if args.audition:
        gap = int(0.55 * SR)
        buf = np.concatenate([np.concatenate([p * scale, np.zeros(gap)]) for p in processed])
        args.audition.parent.mkdir(parents=True, exist_ok=True)
        write_wav24(args.audition, np.stack([buf, buf]))
        print(f"\n  wrote {args.audition}  {len(buf) / SR:.1f} s, {len(processed)} lines")
        return 0

    for m, p in zip(made, processed):
        # Named by the frame it is *placed* on, which is the scheduled frame unless the line
        # had to start early: the mixer places a file from its name and nothing else.
        write_wav24(args.out / f"vo_{m['frame']:04d}.wav", p * scale)
    (args.out / "narration.json").write_text(
        json.dumps(dict(voice=args.voice, base_rate=args.rate, chain=args.chain,
                        lines=made), indent=1, ensure_ascii=False), encoding="utf-8")

    words = sum(m["words"] for m in made)
    speech = sum(m["dur"] for m in made)
    print(f"\n  {len(made)} lines, {words} words, {speech:.1f} s of speech in "
          f"{cues['duration']:.1f} s of film ({speech / cues['duration'] * 100:.0f} %), "
          f"{words / max(speech, 1e-9) * 60:.0f} wpm while actually speaking")
    print(f"  pad trimmed off the front: median "
          f"{np.median([m['pad'] for m in made]) * 1000:.0f} ms, "
          f"worst {max(m['pad'] for m in made) * 1000:.0f} ms")
    print(f"  {hits} take(s) came from the cache, {takes_total - hits} from the network")
    if fitted:
        print(f"  {len(fitted)} line(s) sped up to fit their slot: "
              + ", ".join(f"f{f}{r}" for f, r in fitted))
    if early:
        print(f"  {len(early)} line(s) started early, into silence the line before left: "
              + ", ".join(f"f{f} by {v:.2f} s" for f, v in early))
    print(f"  {len(kept)} line(s) still overrun" if kept else "  every line fits its slot")
    for f, o in kept:
        print(f"    f{f} by {o:.2f} s -- shorten the sentence in the script")
    if suspect:
        print(f"  {len(suspect)} token(s) took longer than {TOKEN_SUSPECT} s "
              f"-- check how they are being read:")
        for f, w, d in suspect:
            print(f"    f{f}  {w!r}  {d:.2f} s")
    else:
        print(f"  no token took longer than {TOKEN_SUSPECT} s; the numbers and units in the "
              f"script are being read as written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
